# Generated by Django 4.2.5 on 2023-09-08 06:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="is_like",
        ),
    ]
